### PR TITLE
Update Javascript Docs

### PR DESCRIPTION
**Pull request by juan-fernandez**
Changes:
- Update docs with new scope yml.
- Add note about setupFilesAfterEnv.
- Make jest / cypress sections easier to find.

### CODE REVIEW

**Comment by KickingTheTV** [comment]
Nice! That was quick!

**Comment by juan-fernandez** [comment]
> Nice! That was quick!

😄 . I'm not 100% convinced about the index though so we might have to iterate on that

**Comment by juan-fernandez** [comment]
@fermayo how do you feel about https://deploy-preview-164--scope-docs.netlify.com/docs/javascript-installation#index ?

**Comment by fermayo** [comment]
> @fermayo how do you feel about https://deploy-preview-164--scope-docs.netlify.com/docs/javascript-installation#index ?

I'd remove the index and just de-indent `Instrumenting your tests` and `Jest`/`Cypress` so they appear on the right side

**Pull request merged**
