### PR TITLE
Java agent installation on tabs

### PR DESCRIPTION
**Pull request by drodriguezhdez**

### CODE REVIEW

**Comment by fermayo** [comment]
I'd still have the `Install` and `Instrument` sections, and have the tabs within those sections. WDYT?

**Comment by drodriguezhdez** [comment]
I'd have everything in one table. As user, it is more comfortable to clic once and have all info at once (at least in Java agent).

Different tables create a rare feeling in the user with something like this:

image

**Comment by fermayo** [comment]
> I'd have everything in one table. As user, it is more comfortable to clic once and have all info at once (at least in Java agent).
> 
> Different tables create a rare feeling in the user with something like this:
> 
> image

Ok, let's at least keep the `Instrumenting your tests` header after the installation steps within each tab

**Comment by drodriguezhdez** [comment]
Done! Ready to check

**Pull request merged**
